version: "3.8"
services:
  ramp-web:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app/public
    ports:
      - 8000:80
  php:
    image: php:7.4-fpm
    volumes:
      - .:/app/public
